ALTER TABLE [User]
ADD CONSTRAINT PK_USERID PRIMARY KEY CLUSTERED (AIID);

ALTER TABLE [UserSettings]
ADD CONSTRAINT PK_USERSETID PRIMARY KEY CLUSTERED (AIID);

ALTER TABLE [UserSubscription]
ADD CONSTRAINT PK_USERSUBID PRIMARY KEY CLUSTERED (AIID);

ALTER TABLE [InAppPurchases]
ADD CONSTRAINT PK_INAPPID PRIMARY KEY CLUSTERED (AIID);

ALTER TABLE [UserNotificationSettings]
ADD CONSTRAINT PK_UseNoteSetID PRIMARY KEY CLUSTERED (AIID);

ALTER TABLE [UserType]
ADD CONSTRAINT PK_UserTypeID PRIMARY KEY CLUSTERED (AIID);

ALTER TABLE [PricingPlan]
ADD CONSTRAINT PK_ID PRIMARY KEY CLUSTERED (AIID);

sp_help pricingplan;
ALTER TABLE [PricingPlan]
drop constraint PK_PricePlanID;

ALTER TABLE [PricingPlan]
ADD CONSTRAINT PK_PricePlanID NONCLUSTERED (PricingPlanID);


ALTER TABLE [USERSETTINGS]
ADD CONSTRAINT FK_UserID
FOREIGN KEY (USERID) REFERENCES [User](AIID);

ALTER TABLE [USERSUBSCRIPTION]
ADD CONSTRAINT FK_User_ID
FOREIGN KEY (USERID) REFERENCES [User](AIID)
FOREIGN KEY (PricingPlanID) REFERENCES PricingPlan(PricingPlanID);
